const BLUETOOTH_MEMBER_UUIDS = new Map([
[0xfeff,"GN Netcom"],
[0xfefe,"GN Hearing A/S"],
[0xfefd,"Gimbal, Inc."],
[0xfefc,"Gimbal, Inc."],
[0xfefb,"Telit Wireless Solutions (Formerly Stollmann E+V GmbH)"],
[0xfefa,"PayPal, Inc."],
[0xfef9,"PayPal, Inc."],
[0xfef8,"Aplix Corporation"],
[0xfef7,"Aplix Corporation"],
[0xfef6,"Wicentric, Inc."],
[0xfef5,"Dialog Semiconductor GmbH"],
[0xfef4,"Google LLC"],
[0xfef3,"Google LLC"],
[0xfef2,"CSR"],
[0xfef1,"CSR"],
[0xfef0,"Intel"],
[0xfeef,"Polar Electro Oy"],
[0xfeee,"Polar Electro Oy"],
[0xfeed,"Tile, Inc."],
[0xfeec,"Tile, Inc."],
[0xfeeb,"Swirl Networks, Inc."],
[0xfeea,"Swirl Networks, Inc."],
[0xfee9,"Quintic Corp."],
[0xfee8,"Quintic Corp."],
[0xfee7,"Tencent Holdings Limited."],
[0xfee6,"Silvair, Inc."],
[0xfee5,"Nordic Semiconductor ASA"],
[0xfee4,"Nordic Semiconductor ASA"],
[0xfee3,"Anki, Inc."],
[0xfee2,"Anki, Inc."],
[0xfee1,"Anhui Huami Information Technology Co., Ltd."],
[0xfee0,"Anhui Huami Information Technology Co., Ltd."],
[0xfede,"Coin, Inc."],
[0xfedd,"Jawbone"],
[0xfedc,"Jawbone"],
[0xfedb,"Perka, Inc."],
[0xfeda,"ISSC Technologies Corp."],
[0xfed9,"Pebble Technology Corporation"],
[0xfed8,"Google LLC"],
[0xfed7,"Broadcom"],
[0xfed6,"Broadcom"],
[0xfed5,"Plantronics Inc."],
[0xfed4,"Apple, Inc."],
[0xfed3,"Apple, Inc."],
[0xfed2,"Apple, Inc."],
[0xfed1,"Apple, Inc."],
[0xfed0,"Apple, Inc."],
[0xfecf,"Apple, Inc."],
[0xfece,"Apple, Inc."],
[0xfecd,"Apple, Inc."],
[0xfecc,"Apple, Inc."],
[0xfecb,"Apple, Inc."],
[0xfeca,"Apple, Inc."],
[0xfec9,"Apple, Inc."],
[0xfec8,"Apple, Inc."],
[0xfec7,"Apple, Inc."],
[0xfec6,"Kocomojo, LLC"],
[0xfec5,"Realtek Semiconductor Corp."],
[0xfec4,"PLUS Location Systems"],
[0xfec3,"360fly, Inc."],
[0xfec2,"Blue Spark Technologies, Inc."],
[0xfec1,"KDDI Corporation"],
[0xfec0,"KDDI Corporation"],
[0xfebf,"Nod, Inc."],
[0xfebe,"Bose Corporation"],
[0xfebd,"Clover Network, Inc"],
[0xfebc,"Dexcom Inc"],
[0xfebb,"adafruit industries"],
[0xfeba,"Tencent Holdings Limited"],
[0xfeb9,"LG Electronics"],
[0xfeb8,"Meta Platforms, Inc."],
[0xfeb7,"Meta Platforms, Inc."],
[0xfeb6,"Vencer Co., Ltd"],
[0xfeb5,"WiSilica Inc."],
[0xfeb4,"WiSilica Inc."],
[0xfeb3,"Taobao"],
[0xfeb2,"Microsoft Corporation"],
[0xfeb1,"Electronics Tomorrow Limited"],
[0xfeb0,"Nest Labs Inc"],
[0xfeaf,"Nest Labs Inc"],
[0xfeae,"Nokia"],
[0xfead,"Nokia"],
[0xfeac,"Nokia"],
[0xfeab,"Nokia"],
[0xfeaa,"Google LLC"],
[0xfea9,"Savant Systems LLC"],
[0xfea8,"Savant Systems LLC"],
[0xfea7,"UTC Fire and Security"],
[0xfea6,"GoPro, Inc."],
[0xfea5,"GoPro, Inc."],
[0xfea4,"Paxton Access Ltd"],
[0xfea3,"ITT Industries"],
[0xfea0,"Google LLC"],
[0xfe9f,"Google LLC"],
[0xfe9e,"Renesas Design Netherlands B.V."],
[0xfe9d,"Mobiquity Networks Inc"],
[0xfe9c,"GSI Laboratories, Inc."],
[0xfe9b,"Samsara Networks, Inc"],
[0xfe9a,"Estimote"],
[0xfe99,"Currant Inc"],
[0xfe98,"Currant Inc"],
[0xfe97,"Tesla Motors Inc."],
[0xfe96,"Tesla Motors Inc."],
[0xfe95,"Xiaomi Inc."],
[0xfe94,"OttoQ In"],
[0xfe93,"OttoQ In"],
[0xfe92,"Jarden Safety & Security"],
[0xfe91,"Shanghai Imilab Technology Co.,Ltd"],
[0xfe90,"JUMA"],
[0xfe8f,"CSR"],
[0xfe8e,"ARM Ltd"],
[0xfe8d,"Interaxon Inc."],
[0xfe8c,"TRON Forum"],
[0xfe8b,"Apple, Inc."],
[0xfe8a,"Apple, Inc."],
[0xfe89,"B&O Play A/S"],
[0xfe88,"SALTO SYSTEMS S.L."],
[0xfe87,"Qingdao Yeelink Information Technology Co., Ltd. ( 青岛亿联客信息技术有限公司 )"],
[0xfe86,"HUAWEI Technologies Co., Ltd"],
[0xfe85,"RF Digital Corp"],
[0xfe84,"RF Digital Corp"],
[0xfe83,"Blue Bite"],
[0xfe82,"Medtronic Inc."],
[0xfe81,"Medtronic Inc."],
[0xfe80,"Doppler Lab"],
[0xfe7f,"Doppler Lab"],
[0xfe7e,"Awear Solutions Ltd"],
[0xfe7d,"Aterica Health Inc."],
[0xfe7c,"Telit Wireless Solutions (Formerly Stollmann E+V GmbH)"],
[0xfe7b,"Orion Labs, Inc."],
[0xfe7a,"Bragi GmbH"],
[0xfe79,"Zebra Technologies"],
[0xfe78,"Hewlett-Packard Company"],
[0xfe77,"Hewlett-Packard Company"],
[0xfe76,"TangoMe"],
[0xfe75,"TangoMe"],
[0xfe74,"unwire"],
[0xfe73,"Abbott (formerly St. Jude Medical, Inc.)"],
[0xfe72,"Abbott (formerly St. Jude Medical, Inc.)"],
[0xfe71,"Plume Design Inc"],
[0xfe70,"Beijing Jingdong Century Trading Co., Ltd."],
[0xfe6f,"LINE Corporation"],
[0xfe6e,"The University of Tokyo"],
[0xfe6d,"The University of Tokyo"],
[0xfe6c,"TASER International, Inc."],
[0xfe6b,"TASER International, Inc."],
[0xfe6a,"Kontakt Micro-Location Sp. z o.o."],
[0xfe69,"Capsle Technologies Inc."],
[0xfe68,"Capsle Technologies Inc."],
[0xfe67,"Lab Sensor Solutions"],
[0xfe66,"Intel Corporation"],
[0xfe65,"CHIPOLO d.o.o."],
[0xfe64,"Siemens AG"],
[0xfe63,"Connected Yard, Inc."],
[0xfe62,"Indagem Tech LLC"],
[0xfe61,"Logitech International SA"],
[0xfe60,"Lierda Science & Technology Group Co., Ltd."],
[0xfe5f,"Eyefi, Inc."],
[0xfe5e,"Plastc Corporation"],
[0xfe5d,"Grundfos A/S"],
[0xfe5c,"million hunters GmbH"],
[0xfe5b,"GT-tronics HK Ltd"],
[0xfe5a,"Cronologics Corporation"],
[0xfe59,"Nordic Semiconductor ASA"],
[0xfe58,"Nordic Semiconductor ASA"],
[0xfe57,"Dotted Labs"],
[0xfe56,"Google LLC"],
[0xfe55,"Google LLC"],
[0xfe54,"Motiv, Inc."],
[0xfe53,"3M"],
[0xfe52,"SetPoint Medical"],
[0xfe51,"SRAM"],
[0xfe50,"Google LLC"],
[0xfe4f,"Molekule, Inc."],
[0xfe4e,"NTT docomo"],
[0xfe4d,"Casambi Technologies Oy"],
[0xfe4c,"Volkswagen AG"],
[0xfe4b,"Signify Netherlands B.V. (formerly Philips Lighting B.V.)"],
[0xfe4a,"OMRON HEALTHCARE Co., Ltd."],
[0xfe49,"SenionLab AB"],
[0xfe48,"General Motors"],
[0xfe47,"General Motors"],
[0xfe46,"B&O Play A/S"],
[0xfe45,"Snapchat Inc"],
[0xfe44,"SK Telecom"],
[0xfe43,"Andreas Stihl AG & Co. KG"],
[0xfe42,"Nets A/S"],
[0xfe41,"Inugo Systems Limited"],
[0xfe40,"Inugo Systems Limited"],
[0xfe3f,"Friday Labs Limited"],
[0xfe3e,"BD Medical"],
[0xfe3d,"BD Medical"],
[0xfe3c,"alibaba"],
[0xfe3b,"Dolby Laboratories"],
[0xfe3a,"TTS Tooltechnic Systems AG & Co. KG"],
[0xfe39,"TTS Tooltechnic Systems AG & Co. KG"],
[0xfe36,"HUAWEI Technologies Co., Ltd"],
[0xfe35,"HUAWEI Technologies Co., Ltd"],
[0xfe34,"SmallLoop LLC"],
[0xfe33,"CHIPOLO d.o.o."],
[0xfe32,"Pro-Mark, Inc."],
[0xfe31,"Volkswagen AG"],
[0xfe30,"Volkswagen AG"],
[0xfe2f,"CRESCO Wireless, Inc"],
[0xfe2e,"ERi,Inc."],
[0xfe2d,"LAMPLIGHT Co., Ltd."],
[0xfe2c,"Google LLC"],
[0xfe2b,"ITT Industries"],
[0xfe2a,"DaisyWorks, Inc."],
[0xfe29,"Gibson Innovations"],
[0xfe28,"Ayla Networks"],
[0xfe27,"Google LLC"],
[0xfe26,"Google LLC"],
[0xfe25,"Apple, Inc."],
[0xfe24,"August Home Inc"],
[0xfe23,"Zoll Medical Corporation"],
[0xfe22,"Zoll Medical Corporation"],
[0xfe21,"Bose Corporation"],
[0xfe20,"Emerson"],
[0xfe1f,"Garmin International, Inc."],
[0xfe1e,"LAMPLIGHT Co., Ltd."],
[0xfe1d,"Illuminati Instrument Corporation"],
[0xfe1c,"NetMedia, Inc."],
[0xfe1b,"Tyto Life LLC"],
[0xfe1a,"Tyto Life LLC"],
[0xfe19,"Google LLC"],
[0xfe18,"Runtime, Inc."],
[0xfe17,"Telit Wireless Solutions GmbH"],
[0xfe16,"Footmarks, Inc."],
[0xfe15,"Amazon.com Services, Inc.."],
[0xfe14,"Flextronics International USA Inc."],
[0xfe13,"Apple Inc."],
[0xfe12,"M-Way Solutions GmbH"],
[0xfe11,"GMC-I Messtechnik GmbH"],
[0xfe10,"LAPIS Technology Co., Ltd."],
[0xfe0f,"Signify Netherlands B.V. (formerly Philips Lighting B.V.)"],
[0xfe0e,"Setec Pty Ltd"],
[0xfe0d,"Procter & Gamble"],
[0xfe0c,"Procter & Gamble"],
[0xfe0b,"ruwido austria gmbh"],
[0xfe0a,"ruwido austria gmbh"],
[0xfe09,"Pillsy, Inc."],
[0xfe08,"Microsoft"],
[0xfe07,"Sonos, Inc."],
[0xfe06,"Qualcomm Technologies, Inc."],
[0xfe05,"CORE Transport Technologies NZ Limited"],
[0xfe04,"Motorola Solutions, Inc."],
[0xfe03,"Amazon.com Services, Inc."],
[0xfe02,"Robert Bosch GmbH"],
[0xfe01,"Duracell U.S. Operations Inc."],
[0xfe00,"Amazon.com Services, Inc."],
[0xfdff,"OSRAM GmbH"],
[0xfdfe,"ADHERIUM(NZ) LIMITED"],
[0xfdfd,"RecursiveSoft Inc."],
[0xfdfc,"Optrel AG"],
[0xfdfb,"Tandem Diabetes Care"],
[0xfdfa,"Tandem Diabetes Care"],
[0xfdf9,"INIA"],
[0xfdf8,"Onvocal"],
[0xfdf7,"HP Inc."],
[0xfdf6,"AIAIAI ApS"],
[0xfdf5,"Milwaukee Electric Tools"],
[0xfdf4,"O. E. M. Controls, Inc."],
[0xfdf3,"Amersports"],
[0xfdf2,"AMICCOM Electronics Corporation"],
[0xfdf1,"LAMPLIGHT Co.,Ltd"],
[0xfdf0,"Google LLC"],
[0xfdef,"ART AND PROGRAM, INC."],
[0xfdee,"Huawei Technologies Co., Ltd."],
[0xfded,"Pole Star"],
[0xfdec,"Mannkind Corporation"],
[0xfdeb,"Syntronix Corporation"],
[0xfdea,"SeeScan, Inc"],
[0xfde9,"Spacesaver Corporation"],
[0xfde8,"Robert Bosch GmbH"],
[0xfde7,"SECOM Co., LTD"],
[0xfde6,"Intelletto Technologies Inc"],
[0xfde5,"SMK Corporation"],
[0xfde4,"JUUL Labs, Inc."],
[0xfde3,"Abbott Diabetes Care"],
[0xfde2,"Google LLC"],
[0xfde1,"Fortin Electronic Systems"],
[0xfde0,"John Deere"],
[0xfddf,"Harman International"],
[0xfdde,"Noodle Technology Inc."],
[0xfddd,"Arch Systems Inc"],
[0xfddc,"4iiii Innovations Inc."],
[0xfddb,"Samsung Electronics Co., Ltd."],
[0xfdda,"MHCS"],
[0xfdd9,"Jiangsu Teranovo Tech Co., Ltd."],
[0xfdd8,"Jiangsu Teranovo Tech Co., Ltd."],
[0xfdd7,"Copeland Cold Chain LP"],
[0xfdd6,"Ministry of Supply"],
[0xfdd5,"Brompton Bicycle Ltd"],
[0xfdd4,"LX Solutions Pty Limited"],
[0xfdd3,"FUBA Automotive Electronics GmbH"],
[0xfdd2,"Bose Corporation"],
[0xfdd1,"Huawei Technologies Co., Ltd"],
[0xfdd0,"Huawei Technologies Co., Ltd"],
[0xfdcf,"Nalu Medical, Inc"],
[0xfdce,"SENNHEISER electronic GmbH & Co. KG"],
[0xfdcd,"Qingping Technology (Beijing) Co., Ltd."],
[0xfdcc,"Shoof Technologies"],
[0xfdcb,"Meggitt SA"],
[0xfdca,"Fortin Electronic Systems"],
[0xfdc9,"Busch-Jaeger Elektro GmbH"],
[0xfdc8,"Hach – Danaher"],
[0xfdc7,"Eli Lilly and Company"],
[0xfdc6,"Eli Lilly and Company"],
[0xfdc5,"Automatic Labs"],
[0xfdc4,"Simavita (Aust) Pty Ltd"],
[0xfdc3,"Baidu Online Network Technology (Beijing) Co., Ltd"],
[0xfdc2,"Baidu Online Network Technology (Beijing) Co., Ltd"],
[0xfdc1,"Hunter Douglas"],
[0xfdc0,"Hunter Douglas"],
[0xfdbf,"California Things Inc."],
[0xfdbe,"California Things Inc."],
[0xfdbd,"Clover Network, Inc."],
[0xfdbc,"Emerson"],
[0xfdbb,"Profoto"],
[0xfdb8,"LivaNova USA Inc."],
[0xfdb7,"LivaNova USA Inc."],
[0xfdb6,"GWA Hygiene GmbH"],
[0xfdb5,"ECSG"],
[0xfdb4,"HP Inc"],
[0xfdb3,"Audiodo AB"],
[0xfdb2,"Portable Multimedia Ltd"],
[0xfdb1,"Oura Health Ltd"],
[0xfdb0,"Oura Health Ltd"],
[0xfdaf,"Wiliot LTD"],
[0xfdae,"Houwa System Design, k.k."],
[0xfdad,"Houwa System Design, k.k."],
[0xfdac,"Tentacle Sync GmbH"],
[0xfdab,"Xiaomi Inc."],
[0xfdaa,"Xiaomi Inc."],
[0xfda9,"Rhombus Systems, Inc."],
[0xfda8,"PSA Peugeot Citroën"],
[0xfda7,"WWZN Information Technology Company Limited"],
[0xfda6,"WWZN Information Technology Company Limited"],
[0xfda5,"Neurostim OAB, Inc."],
[0xfda4,"Inseego Corp."],
[0xfda3,"Inseego Corp."],
[0xfda2,"Groove X, Inc"],
[0xfda1,"Groove X, Inc"],
[0xfda0,"Secugen Corporation"],
[0xfd9f,"VitalTech Affiliates LLC"],
[0xfd9e,"The Coca-Cola Company"],
[0xfd9d,"Gastec Corporation"],
[0xfd9c,"Huawei Technologies Co., Ltd."],
[0xfd9b,"Huawei Technologies Co., Ltd."],
[0xfd9a,"Huawei Technologies Co., Ltd."],
[0xfd99,"ABB Oy"],
[0xfd98,"Disney Worldwide Services, Inc."],
[0xfd97,"June Life, Inc."],
[0xfd96,"Google LLC"],
[0xfd95,"Rigado"],
[0xfd94,"Hewlett Packard Enterprise"],
[0xfd93,"Bayerische Motoren Werke AG"],
[0xfd92,"Qualcomm Technologies International, Ltd. (QTIL)"],
[0xfd91,"Groove X, Inc."],
[0xfd90,"Guangzhou SuperSound Information Technology Co.,Ltd"],
[0xfd8e,"Motorola Solutions"],
[0xfd8d,"quip NYC Inc."],
[0xfd8c,"Google LLC"],
[0xfd8b,"Jigowatts Inc."],
[0xfd8a,"Signify Netherlands B.V."],
[0xfd89,"Urbanminded LTD"],
[0xfd88,"Urbanminded LTD"],
[0xfd87,"Google LLC"],
[0xfd86,"Abbott"],
[0xfd85,"Husqvarna AB"],
[0xfd84,"Tile, Inc."],
[0xfd83,"iNFORM Technology GmbH"],
[0xfd82,"Sony Corporation"],
[0xfd81,"CANDY HOUSE, Inc."],
[0xfd80,"Phindex Technologies, Inc"],
[0xfd7f,"Husqvarna AB"],
[0xfd7e,"Samsung Electronics Co., Ltd."],
[0xfd7d,"Center for Advanced Research Wernher Von Braun"],
[0xfd7c,"Toshiba Information Systems(Japan) Corporation"],
[0xfd7b,"WYZE LABS, INC."],
[0xfd7a,"Withings"],
[0xfd79,"Withings"],
[0xfd78,"Withings"],
[0xfd77,"Withings"],
[0xfd76,"Insulet Corporation"],
[0xfd75,"Insulet Corporation"],
[0xfd74,"BRControls Products BV"],
[0xfd73,"BRControls Products BV"],
[0xfd72,"Logitech International SA"],
[0xfd71,"GN Hearing A/S"],
[0xfd70,"GuangDong Oppo Mobile Telecommunications Corp., Ltd"],
[0xfd6f,"Apple, Inc."],
[0xfd6e,"Polidea sp. z o.o."],
[0xfd6d,"Sigma Elektro GmbH"],
[0xfd6c,"Samsung Electronics Co., Ltd."],
[0xfd6b,"rapitag GmbH"],
[0xfd6a,"Emerson"],
[0xfd69,"Samsung Electronics Co., Ltd"],
[0xfd68,"Ubique Innovation AG"],
[0xfd67,"Montblanc Simplo GmbH"],
[0xfd66,"Zebra Technologies Corporation"],
[0xfd65,"Razer Inc."],
[0xfd64,"INRIA"],
[0xfd63,"Google LLC"],
[0xfd62,"Google LLC"],
[0xfd61,"Arendi AG"],
[0xfd60,"Sercomm Corporation"],
[0xfd5f,"Meta Platforms Technologies, LLC"],
[0xfd5e,"Tapkey GmbH"],
[0xfd5d,"maxon motor ltd."],
[0xfd5c,"React Mobile"],
[0xfd5b,"V2SOFT INC."],
[0xfd5a,"Samsung Electronics Co., Ltd."],
[0xfd59,"Samsung Electronics Co., Ltd."],
[0xfd58,"Volvo Car Corporation"],
[0xfd57,"Volvo Car Corporation"],
[0xfd56,"Resmed Ltd"],
[0xfd55,"Braveheart Wireless, Inc."],
[0xfd54,"Qingdao Haier Technology Co., Ltd."],
[0xfd53,"PCI Private Limited"],
[0xfd52,"UTC Fire and Security"],
[0xfd51,"UTC Fire and Security"],
[0xfd50,"Hangzhou Tuya Information  Technology Co., Ltd"],
[0xfd4f,"SONITOR TECHNOLOGIES AS"],
[0xfd4e,"70mai Co.,Ltd."],
[0xfd4d,"70mai Co.,Ltd."],
[0xfd4c,"Adolf Wuerth GmbH & Co KG"],
[0xfd4b,"Samsung Electronics Co., Ltd."],
[0xfd4a,"Sigma Elektro GmbH"],
[0xfd49,"Panasonic Corporation"],
[0xfd48,"Geberit International AG"],
[0xfd47,"Liberty Global Inc."],
[0xfd46,"Lemco IKE"],
[0xfd45,"GB Solution co.,Ltd"],
[0xfd44,"Apple Inc."],
[0xfd43,"Apple Inc."],
[0xfd42,"Globe (Jiangsu) Co.,Ltd"],
[0xfd41,"Amazon Lab126"],
[0xfd40,"Beflex Inc."],
[0xfd3f,"Cognosos, Inc"],
[0xfd3e,"Pure Watercraft, inc."],
[0xfd3d,"Woan Technology (Shenzhen) Co., Ltd."],
[0xfd3c,"Redline Communications Inc."],
[0xfd3b,"Verkada Inc."],
[0xfd3a,"Verkada Inc."],
[0xfd39,"PREDIKTAS"],
[0xfd38,"Danfoss A/S"],
[0xfd37,"TireCheck GmbH"],
[0xfd36,"Google LLC"],
[0xfd35,"Transsion Holdings Limited"],
[0xfd34,"Aerosens LLC."],
[0xfd33,"DashLogic, Inc."],
[0xfd32,"Gemalto Holding BV"],
[0xfd31,"LG Electronics Inc."],
[0xfd30,"Sesam Solutions BV"],
[0xfd2f,"Bitstrata Systems Inc."],
[0xfd2e,"Bitstrata Systems Inc."],
[0xfd2d,"Xiaomi Inc."],
[0xfd2c,"The Access Technologies"],
[0xfd2b,"The Access Technologies"],
[0xfd2a,"Sony Corporation"],
[0xfd29,"Asahi Kasei Corporation"],
[0xfd28,"Julius Blum GmbH"],
[0xfd27,"Integrated Illumination Systems, Inc."],
[0xfd26,"Novo Nordisk A/S"],
[0xfd25,"GD Midea Air-Conditioning Equipment Co., Ltd."],
[0xfd24,"GD Midea Air-Conditioning Equipment Co., Ltd."],
[0xfd23,"DOM Sicherheitstechnik GmbH & Co. KG"],
[0xfd22,"Huawei Technologies Co., Ltd."],
[0xfd21,"Huawei Technologies Co., Ltd."],
[0xfd20,"GN Hearing A/S"],
[0xfd1f,"3M"],
[0xfd1e,"Plume Design Inc."],
[0xfd1d,"Samsung Electronics Co., Ltd"],
[0xfd1c,"Brady Worldwide Inc."],
[0xfd1b,"Helios Sports, Inc."],
[0xfd1a,"CSIRO"],
[0xfd19,"Smith & Nephew Medical Limited"],
[0xfd18,"LEGIC Identsystems AG"],
[0xfd17,"LEGIC Identsystems AG"],
[0xfd16,"Sensitech, Inc."],
[0xfd15,"Panasonic Corporation"],
[0xfd14,"BRG Sports, Inc."],
[0xfd13,"BRG Sports, Inc."],
[0xfd12,"AEON MOTOR CO.,LTD."],
[0xfd11,"AEON MOTOR CO.,LTD."],
[0xfd10,"AEON MOTOR CO.,LTD."],
[0xfd0f,"AEON MOTOR CO.,LTD."],
[0xfd0e,"HerdDogg, Inc"],
[0xfd0d,"Blecon Ltd"],
[0xfd0c,"OSM HK Limited"],
[0xfd0b,"Luminostics, Inc."],
[0xfd0a,"Luminostics, Inc."],
[0xfd09,"Cousins and Sears LLC"],
[0xfd08,"Bull Group Incorporated Company"],
[0xfd07,"Swedlock AB"],
[0xfd06,"RACE-AI LLC"],
[0xfd05,"Qualcomm Technologies, Inc."],
[0xfd04,"Shure Inc."],
[0xfd03,"Quuppa Oy"],
[0xfd02,"LEGO System A/S"],
[0xfd01,"Sanvita Medical Corporation"],
[0xfd00,"FUTEK Advanced Sensor Technology, Inc."],
[0xfcff,"701x"],
[0xfcfe,"Sonova Consumer Hearing GmbH"],
[0xfcfd,"Barrot Technology Co.,Ltd."],
[0xfcfc,"Barrot Technology Co.,Ltd."],
[0xfcfb,"Shenzhen Benwei Media Co., Ltd."],
[0xfcfa,"Leupold & Stevens, Inc."],
[0xfcf9,"Leupold & Stevens, Inc."],
[0xfcf8,"Honor Device Co., Ltd."],
[0xfcf7,"Honor Device Co., Ltd."],
[0xfcf6,"The Linux Foundation"],
[0xfcf5,"Trident Communication Technology, LLC"],
[0xfcf4,"Allegion"],
[0xfcf3,"Armatura LLC"],
[0xfcf2,"Bitwards Oy"],
[0xfcf1,"Google LLC"],
[0xfcf0,"Security Enhancement Systems, LLC"],
[0xfcef,"Divesoft s.r.o."],
[0xfcee,"Velentium, LLC"],
[0xfced,"Workaround Gmbh"],
[0xfcec,"Griffwerk GmbH"],
[0xfceb,"Avi-On"],
[0xfcea,"Chess Wise B.V."],
[0xfce9,"MindRhythm, Inc."],
[0xfce8,"ITT Industries"],
[0xfce7,"TKH Security B.V."],
[0xfce6,"Guard RFID Solutions Inc."],
[0xfce5,"Samsara Networks, Inc"],
[0xfce4,"Samsara Networks, Inc"],
[0xfce3,"Smith & Nephew Medical Limited"],
[0xfce2,"Baracoda Daily Healthtech"],
[0xfce1,"Sony Group Corporation"],
[0xfce0,"Akciju sabiedriba SAF TEHNIKA"],
[0xfcdf,"NIO USA, Inc."],
[0xfcde,"ARCTOP, INC."],
[0xfcdd,"Mobilaris AB"],
[0xfcdc,"Amazon.com Services, LLC"],
[0xfcdb,"aconno GmbH"],
[0xfcda,"Draeger"],
[0xfcd9,"Huso, INC"],
[0xfcd8,"Appex Factory S.L."],
[0xfcd7,"PowerPal Pty Ltd"],
[0xfcd6,"SWISSINNO SOLUTIONS AG"],
[0xfcd5,"Nortek Security & Control"],
[0xfcd4,"OMRON HEALTHCARE"],
[0xfcd3,"Fisher & Paykel Healthcare"],
[0xfcd2,"Allterco Robotics ltd"],
[0xfcd1,"Shenzhen Benwei Media Co.,Ltd."],
[0xfcd0,"Laerdal Medical AS"],
[0xfccf,"Google LLC"],
[0xfcce,"Luna Health, Inc."],
[0xfccd,"Marshall Group AB"],
[0xfccb,"TOTO LTD."],
[0xfcca,"Cosmed s.r.l."],
[0xfcc9,"SkyHawke Technologies"],
[0xfcc8,"Allthenticate, Inc."],
[0xfcc7,"PB INC."],
[0xfcc6,"Wiliot LTD."],
[0xfcc5,"OMRON(DALIAN) CO,.LTD."],
[0xfcc4,"OMRON(DALIAN) CO,.LTD."],
[0xfcc3,"HP Inc."],
[0xfcc2,"Qualcomm Technologies, Inc."],
[0xfcc1,"TIMECODE SYSTEMS LIMITED"],
[0xfcc0,"Xiaomi Inc."],
[0xfcbf,"ASSA ABLOY Opening Solutions Sweden AB"],
[0xfcbe,"Musen Connect, Inc."],
[0xfcbd,"Toshiba Corporation"],
[0xfcbc,"Drowsy Digital, Inc."],
[0xfcbb,"SharkNinja Operating LLC"],
[0xfcba,"BlueID GmbH"],
[0xfcb9,"Lumi United Technology Co., Ltd"],
[0xfcb8,"Ribbiot, INC."],
[0xfcb7,"T-Mobile USA"],
[0xfcb6,"OMRON HEALTHCARE Co., Ltd."],
[0xfcb5,"OMRON HEALTHCARE Co., Ltd."],
[0xfcb4,"OMRON HEALTHCARE Co., Ltd."],
[0xfcb3,"SWEEN"],
[0xfcb2,"Apple Inc."],
[0xfcb1,"Google LLC"],
[0xfcb0,"Ford Motor Company"],
[0xfcaf,"AltoBeam Inc."],
[0xfcae,"Imagine Marketing Limited"],
[0xfcad,"Beijing 99help Safety Technology Co., Ltd"],
[0xfcac,"IRISS INC."],
[0xfcab,"IRISS INC."],
[0xfcaa,"Spintly, Inc."],
[0xfca9,"Medtronic Inc."],
[0xfca8,"Medtronic Inc."],
[0xfca7,"Hubble Network Inc."],
[0xfca6,"Hubble Network Inc."],
[0xfca5,"HAYWARD INDUSTRIES, INC."],
[0xfca4,"HP Inc."],
[0xfca3,"Gunnebo Aktiebolag"],
[0xfca2,"Meizu Technology Co., Ltd."],
[0xfca1,"PF SCHWEISSTECHNOLOGIE GMBH"],
[0xfca0,"Apple Inc."],
[0xfc9f,"Delta Development Team, Inc"],
[0xfc9e,"Dell Computer Corporation"],
[0xfc9d,"Lenovo (Singapore) Pte Ltd."],
[0xfc9b,"Merry Electronics (S) Pte Ltd"],
[0xfc9a,"Koppli AB"],
[0xfc99,"Badger Meter"],
[0xfc98,"Ruuvi Innovations Ltd."],
[0xfc97,"Japan Display Inc."],
[0xfc96,"LEGO System A/S"],
[0xfc95,"Hippo Camp Software Ltd."],
[0xfc94,"Apple Inc."],
[0xfc93,"Komatsu Ltd."],
[0xfc92,"Furuno Electric Co., Ltd."],
[0xfc91,"Samsung Electronics Co., Ltd."],
[0xfc90,"Wiliot LTD."],
[0xfc8f,"Bose Corporation"],
[0xfc8e,"Blue Iris Labs, Inc."],
[0xfc8d,"Caire Inc."],
[0xfc8c,"VusionGroup"],
[0xfc8b,"Kaspersky Lab Middle East FZ-LLC"],
[0xfc8a,"Intel Corporation"],
[0xfc89,"Intel Corporation"],
[0xfc88,"CCC del Uruguay"],
[0xfc87,"Samsara Networks, Inc"],
[0xfc86,"Samsara Networks, Inc"],
[0xfc85,"Zhejiang Huanfu Technology Co., LTD"],
[0xfc84,"NINGBO FOTILE KITCHENWARE CO., LTD."],
[0xfc83,"iHealth Labs, Inc."],
[0xfc82,"Zwift, Inc."],
[0xfc81,"Axon Enterprise, Inc."],
[0xfc80,"TELE System Communications Pte. Ltd."],
[0xfc7f,"Southco"],
[0xfc7e,"Harman International"],
[0xfc7d,"MML US, Inc"],
[0xfc7c,"Motorola Mobility, LLC"],
[0xfc7b,"Testo SE & Co. KGaA"],
[0xfc7a,"Outshiny India Private Limited"],
[0xfc79,"LG Electronics Inc."],
[0xfc78,"DHL"],
[0xfc77,"SING SUN TECHNOLOGY (INTERNATIONAL) LIMITED"],
[0xfc76,"Weber-Stephen Products LLC"],
[0xfc75,"Xiaomi Inc."],
[0xfc74,"EMBEINT INC"],
[0xfc73,"Google LLC"],
[0xfc72,"iodyne, LLC"],
[0xfc71,"Hive-Zox International SA"],
[0xfc70,"MOTIVE TECHNOLOGIES, INC."],
[0xfc6f,"NextSense, Inc."],
[0xfc6e,"stryker"],
[0xfc6d,"MOTIVE TECHNOLOGIES, INC."],
[0xfc6c,"Powerstick.com"],
[0xfc6b,"Sonos Inc"],
[0xfc6a,"Sonos Inc"],
[0xfc69,"Harman International"],
[0xfc68,"RIGH, INC."],
[0xfc67,"Guangdong Hengqin Xingtong Technology Co.,ltd."],
[0xfc66,"Xiaomi Inc."],
[0xfc65,"Robor Electronics B.V."],
[0xfc64,"Volvo Technology AB"],
[0xfc63,"Volvo Technology AB"],
[0xfc62,"SPRiNTUS GmbH"],
[0xfc61,"QIKCONNEX LLC"],
[0xfc60,"Ohme Operations UK Limited"],
[0xfc5f,"PI-CRYSTAL INC."],
[0xfc5e,"KUBU SMART LIMITED"],
[0xfc5d,"GP Acoustics International Limited"],
[0xfc5c,"PLASTIC RESEARCH AND DEVELOPMENT CORPORATION"],
[0xfc5b,"Time Location Systems AS"],
[0xfc5a,"LAST LOCK INC."],
[0xfc59,"Ant Group Co., Ltd."],
[0xfc58,"Shenzhen Minew Technologies Co., Ltd."],
[0xfc57,"Ambient Life Inc."],
[0xfc56,"Google LLC"],
[0xfc55,"BYD Company Limited"],
[0xfc54,"Shenzhen Yinwang Intelligent Technologies Co., Ltd."],
[0xfc53,"LEGIC Identsystems AG"],
[0xfc52,"LG Electronics Inc."],
[0xfc51,"Ant Group Co., Ltd."],
[0xfc50,"Ant Group Co., Ltd."],
[0xfc4f,"WaveRF, Corp."],
[0xfc4e,"Lodestar Technology Inc."],
[0xfc4d,"Lodestar Technology Inc."],
[0xfc4c,"HP Inc."],
[0xfc4b,"WinMagic Inc."],
[0xfc4a,"Shenzhen Shokz Co.,Ltd."],
[0xfc49,"Golioth, Inc."],
[0xfc48,"Michelin"],
[0xfc47,"Shanghai Ingeek Technology Co., Ltd."],
[0xfc46,"Xiaomi"],
[0xfc45,"Mitsubishi Electric Corporation"],
[0xfc44,"Block, Inc."],
[0xfc43,"Atmosic Technologies, Inc."],
[0xfc41,"Yoto Limited"],
[0xfc3f,"Milwaukee Electric Tools"],
[0xfc3e,"Google LLC"],
[0xfc3d,"Reelables, Inc."],
[0xfc3c,"Eforthink Technology Co., Ltd."],
[0xfc3b,"BONX INC."],
[0xfc3a,"C.O.B.O. SpA"],
[0xfc39,"Harman International"],
[0xfc38,"SetPoint Medical"],
[0xfc37,"TANlock GmbH"],
[0xfc36,"PharmaSens AG"],
[0xfc35,"Metabowerke GmbH"],
[0xfc34,"Mitsubishi Electric Corporation"],
[0xfc32,"InPlay, Inc."]
]);